### ISSUE TITLE
Lame fighting actions and pitifully inadequate choice for characters

### ISSUE THREAD

**Issue by ImKeTT** [RuoyuChen10/FightingGame-FTG4.50#1]
The fighting action designs are so lame !! And fighting characters are so limited to pick!! I believe adding MORE novel and interesting fighting actions (e.g., flying kick, combination blow) for MORE characters (e.g., iron man, spider man) is the priority !

**Comment by RuoyuChen10** [comment]
> The fighting action designs are so lame !! And fighting characters are so limited to pick!! I believe adding MORE novel and interesting fighting actions (e.g., flying kick, combination blow) for MORE characters (e.g., iron man, spider man) is the priority !

You are so funny, Tu Haoqin. I don't know how to begin writing a response.
