### ISSUE TITLE
国防科大也研究游戏吗

### ISSUE THREAD

**Issue by peterwangx** [RuoyuChen10/FightingGame-FTG4.50#2]
兄弟，国防科大也研究游戏吗

**Comment by RuoyuChen10** [comment]
> 兄弟，国防科大也研究游戏吗

我们这里是中国科学院大学，简称国科大，不是国防科大。一般主要是研究强化学习算法吧，游戏只是一个测试平台，比如AlphaGo是打围棋游戏的。
